<?php

/**
 * @file
 * Contains commerce_akeneo_family.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\commerce_akeneo_family\Controller\CommerceAkeneoFamilyDrush;
use Drupal\commerce_akeneo_family\Controller\CommerceAkeneoFamilyBatch;
use Drupal\commerce_akeneo_family\Plugins\Services\CommerceAkeneoFamilyServices;
/**
 * Implements hook_help().
 */
function commerce_akeneo_family_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_akeneo_family module.
    case 'help.page.commerce_akeneo_family':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add support for Family.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_drush_command().
 */
function commerce_akeneo_family_drush_command() {
	CommerceAkeneoFamilyDrush::commerce_akeneo_family_drush_command();
}

/**
 * Implements hook_queue_info().
 */
function commerce_akeneo_family_queue_info() {
	CommerceAkeneoFamilyBatch::commerce_akeneo_family_queue_info();
}