<?php

/**
 * @file
 * Contains commerce_akeneo_taxonomy.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\commerce_akeneo_taxonomy\Controller\CommerceAkeneoTaxonomy;
$taxonomy = new CommerceAkeneoTaxonomy();
//$taxonomy->commerce_akeneo_taxonomy_handle_service('abc','category', 'name', '');

/**
 * Implements hook_help().
 */
function commerce_akeneo_taxonomy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_akeneo_taxonomy module.
    case 'help.page.commerce_akeneo_taxonomy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add support for Taxonomy (attribute options and catalog).') . '</p>';
      return $output;

    default:
  }
}
/**
 * Implements hook_ctools_plugin_directory().
 */
function commerce_akeneo_taxonomy_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'commerce_akeneo') {
    return "plugins/$plugin_type";
  }
}
