<?php

/**
 * @file
 * Contains commerce_akeneo_field.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_akeneo_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_akeneo_field module.
    case 'help.page.commerce_akeneo_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add support for Field (numeric, text, file, image, ...).') . '</p>';
      return $output;

    default:
  }
}
